version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrator
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/bookstore?sslmode=disable"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore

  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      - db
    command:
      [
        "migrate",
        "-path",
        "/db/migrations",
        "-database",
        "postgres://postgres:password@db:5432/bookstore?sslmode=disable",
        "up",
      ]
    restart: "no"
