version: 2.1
orbs:
  go: circleci/go@1.7.3

jobs:
  build_and_test: # this can be any name you choose
    executor:
      name: go/default # Use the default executor from the orb
      tag: "1.19.2" # Specify a version tag
    steps:
      - checkout # checkout source code
      - go/load-cache # Load cached Go modules.
      - go/mod-download # Run 'go mod download'.
      - go/save-cache # Save Go modules to cache.
      - go/test: # Runs 'go test ./...' but includes extensive parameterization for finer tuning.
          covermode: atomic
          failfast: true
          race: true
      - persist_to_workspace:
          root: ~/project
          paths: .

workflows:
  test_my_app:
    jobs:
      - build_and_test
      # - deploy:
      #     requires:
      #       - build_and_test # only deploy if the build_and_test job has completed
      #     filters:
      #       branches:
      #         only: main # only deploy when on main
# version: 2.1

# # Reusable commands
# commands:
#   build_and_push_image:
#     description: "Build and Push image"
#     steps:
#       - setup_remote_docker:
#           version: 20.10.7
#           docker_layer_caching: true
#       - run:
#           name: Build Docker image
#           command: docker build -t your_username/bookstore-app:$CIRCLE_SHA1 .
#       - run:
#           name: Login to DockerHub
#           command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
#       - run:
#           name: Push Docker image
#           command: docker push your_username/bookstore-app:$CIRCLE_SHA1

# # Orchestrate our job run order with workflows
# workflows:
#   version: 2
#   build_and_deploy:
#     jobs:
#       - build

# # Define the jobs
# jobs:
#   build:
#     docker:
#       - image: circleci/golang:1.17
#     working_directory: /go/src/github.com/your_username/bookstore-app
#     steps:
#       - checkout
#       - build_and_push_image
